[tool.poetry]
name = "osmose"
version = "0.1.0"
description = ""
authors = ["Noémie Lehuby <noemie.lehuby@zaclys.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
xmltodict = "^0.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
