dist: trusty
language: python
python:
  - "3.6"

before_install:
  - cd ci && ./install.sh
  - export PATH=$PATH:$PWD/
  - xsv --version
  - osm_transit_extractor --version

script:
  - cd .. && ./run_all.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  keep-history: true
  on:
    branch: master
