name: Generate and deploy IDF data

on:
  schedule:
    - cron:  '0 18 * * 5'
  push:
    branches-ignore:
      - 'gh-pages'

      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install osmium
      run: |
        sudo apt-get install osmium-tool
    - name: Install xsv
      run: |
        wget --quiet https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
        tar -zxvf xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
        pwd >> $GITHUB_PATH
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH                         
    - name: Install dependencies && generate IDF data      
      env:
        Osmose_idf_auth: ${{ secrets.Osmose_idf_auth }}
      run: |
        cd ci && ./install.sh 
        cd ..
        ./run_all.sh
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
